### ISSUE TITLE
Can I please be added as a collaborator?

### ISSUE THREAD

**Issue by niftylettuce** [segmentio/superagent-retry#27]
I'd like to merge https://github.com/segmentio/superagent-retry/pull/15 and also help maintain the package and releases on NPM.  I use `superagent` in `axe` and need retry to work in the browser.  I'd also like to update the version of superagent used among other things.

Could you add me as a collaborator here on GitHub and also on NPM.  Username is "niftylettuce".

cc @calvinfo @gjohnson

**Comment by niftylettuce** [comment]
Nevermind, the latest version of `superagent` has built-in retry method https://github.com/visionmedia/superagent

**Comment by gjohnson** [comment]
Hey @niftylettuce, thanks for pointing this out. We should archive/deprecate this module @calvinfo.
